### ISSUE TITLE
Fabric support

### ISSUE THREAD

**Issue by nervich** [raoulvdberge/refinedstorageaddons#101]
### Describe your enhancement

I've been searching for a fabric wireless grid mod for about 2 hours now with no luck. I even tried to translate it myself but with no coding experience that was nothing, of course. I'm BEGGING you to port it to fabric. If a wireless grid mod already exists for fabric (1.19(.3)) and I somehow didn't find it, please let me know!

**Comment by raoulvdberge** [comment]
Check RS 2 on github and the faq on there as well.
