### ISSUE TITLE
Network Transmitter that handles more than one card.

### ISSUE THREAD

**Issue by wiredsalad** [raoulvdberge/refinedstorageaddons#102]
### Describe your enhancement

I'm aware that this has been brought up before, but since that's been 5 years ago, I was wondering if there's a chance for this feature to be reconsidered? 
Something like an upgrade to allow a total of 3 cards, in my opinion, would be a wonderful improvement. As it is, I have 6 transmitters holding one card each, and I'm having a hard time finding a good reason why that's the case (other than the dev simply not wanting it 'cause it takes more work, which is more than fair, but I'm also curious if there are other reasons). 

Thanks!

**Comment by raoulvdberge** [comment]
No, I haven't changed my mind on this.
