### ISSUE TITLE
[Suggestion] Bigger pattern storage 

### ISSUE THREAD

**Issue by llloyd4** [raoulvdberge/refinedstorageaddons#11]
9 patterns per IO is just a wee bit to small. As a follower of Direwolfism (all things are autocraftable with ingenuity snd a butt tonne of mods.) I have an entire wall of IOs, literally and would love to see that shrunk. Old school AE used a multi block setup of cpu and storage blocks. Maybe create a similar system? Or whatever you consider fair. :)

**Comment by way2muchnoise** [comment]
https://github.com/TechReborn/RebornStorage and https://minecraft.curseforge.com/projects/rebornstorage

**Comment by llloyd4** [comment]
O.o *grabs! * All I need now is the infinite range upgrade for the wireless Crafter and life will, for now, be complete. :D Thank you!
