### ISSUE TITLE
[1.20.1] Can't bind mouse buttons to open wireless crafting grid

### ISSUE THREAD

**Issue by jinkhya** [raoulvdberge/refinedstorageaddons#110]
### Describe the bug

Hello,
When I set [Button 4] or [Button 5] from mouse it doesn't do anything.
For comparison, those work to open sophisticated backpacks or to open ftb quests.
Thanks in advance,
Jin

### How can we reproduce this bug or crash?

1. Make an instance with just RS/RSaddons
2. Bind a mouse button that is not configured to output a key. So in keybinds it should look like [Button 4]
3. Try to open the wireless crafting grid with it.

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.1.3 (same on latest forge)

### What Refined Storage Addons version is this happening on?

0.10.0

**Comment by MaximilienMoritz** [comment]
Same issue here, but on 1.19.2

**Comment by raoulvdberge** [comment]
Hello, this has been fixed for RS 2. 

See: https://github.com/refinedmods/refinedstorage2/issues/665
