### ISSUE TITLE
Why isn't this part of normal refined storage?

### ISSUE THREAD

**Issue by CptShadows** [raoulvdberge/refinedstorageaddons#116]
### Describe your enhancement

As much as I absolutely love your mod (if I had to choose literally two mods, this + mekanism would be the ones), why isn't this just part of normal refined storage? I've just been playing on a modpack where I added refined storage manually, and was confused why the wireless crafting grid wasn't in my REI list.. just to find out I need a dedicated mod **just** for the wireless crafting grid? :/

**Comment by raoulvdberge** [comment]
Originally RS Addons was planned to receive more content, but that never happened due to time constraints.

This situation will change with RS 2.
