### ISSUE TITLE
Wireless Crafting Grid Dupe/Void

### ISSUE THREAD

**Issue by Trold220704** [raoulvdberge/refinedstorageaddons#117]
### Describe the bug

When using Wireless Crafting gird, If you put items in the 2 first slots of the crafting grid close it and reopen it, it will still be there but there will also be the same in the 2 boxes on the side of the screen. This may sound confusing so i have added a video that shows it

In the video i use creative items but it also happens with the none creative versions

https://github.com/refinedmods/refinedstorageaddons/assets/109646820/409a98d5-abd8-4181-b9c4-998eadc95ac5

### How can we reproduce this bug or crash?

1. Open Wireless Crafting Gird
2. Place item in either the first or second slot (or both)
3. Close and open Wireless Crafting Grid and it will be dupped

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge version is this happening on?

47.2.20

### What Refined Storage Addons version is this happening on?

0.10.0

**Comment by raoulvdberge** [comment]
Not caused by RS.
Update RS Insert Export Upgrade
