### ISSUE TITLE
Upgrading a map in the Wireless Crafting Grid crashes Minecraft.

### ISSUE THREAD

**Issue by kd8lvt** [raoulvdberge/refinedstorageaddons#12]
Here is my mod-list: [Mod List](http://kd8lvt.kdray.pro/projects/modpacks/Adventure%20Awaits/Mod%20List%20%28as%20of%200.0.1%29.html)
Here is my crash report: [Crash Report](https://pastebin.com/SrckpTjb)
Here is my full log: [Full Log](https://pastebin.com/WdSbNpSf)
Possibly related information:
1. I have Quark, which I think is the mod I have that lets you hover over a map to see it in your inventory. Not sure if related, but probably is.
2. I also have Foam-Fix Anarchy.
3. It started crashing the moment I made the recipe valid.
4. I'm on a server
5. It did not crash the server, just my client.
6. The server timed me out before I actually crashed. Never seen that happen before.

If you need any more information, I'd be happy to provide!

**Comment by raoulvdberge** [comment]
I can't reproduce this, so it's probably a crossmod problem.
