### ISSUE TITLE
suggestion-multicard network transmitter

### ISSUE THREAD

**Issue by PurpleHel** [raoulvdberge/refinedstorageaddons#13]
It's really annoying and unaesthetic to have to have a separate transmitter for each networked location. A single transmitter that could hold multiple cards would be excellent. I don't even care if I have to put equivalent resources to a whole network transmitter into it every time I add a card. I just really want a single block solution, or at least something better than the 9 transmitters I've got now! (each powering an infinite wireless antenna in a different dimension.)

**Comment by raoulvdberge** [comment]
I have to think about this.

**Comment by PurpleHel** [comment]
*nod* Even just like, a "network rack" or something, that the player still has to build the transmitter and upgrades and network card, but then can integrate it into a block with other transmitters. And the power draw could increase by the current transmitter draw for every transmitter in the "rack", that'd be fine by me. I just really want the multiple transmitters to take less space. :)

**Comment by raoulvdberge** [comment]
I decided against this, sorry.

**Comment by PurpleHel** [comment]
Sorry to hear it.
