### ISSUE TITLE
Suggestion - An upgrade to the Infinite Wireless Transmitter.

### ISSUE THREAD

**Issue by GGearZZ** [raoulvdberge/refinedstorageaddons#17]
Hello. Would it be possible to an an upgrade slot to the Infinite Wireless Transmitter for the Interdimentional Upgrade so that you can access your network from other dimenstions? Thank you for you considerations.

**Comment by raoulvdberge** [comment]
No

**Comment by GGearZZ** [comment]
Again, thank you for your time and considerations.
