### ISSUE TITLE
Wireless Crafting Grid / Vanilla Enchanting Table Interaction

### ISSUE THREAD

**Issue by shawnbyday** [raoulvdberge/refinedstorageaddons#19]
If you right click the vanilla enchanting table whilst holding your Wireless Crafting Grid it first opens the enchanting table interface then pops up the Wireless Crafting Grid. I haven't noticed this with any other interactive blocks. I'm running a custom created mod pack on 1.12.2 with forge-14.23.1.2566. If you need any other information about the bug just let me know. This bug doesn't bother me but just trying to do my part :)

**Comment by raoulvdberge** [comment]
I can't reproduce this...
