### ISSUE TITLE
[Suggestion] Configurable Wireless Crafting Grid Power Storage

### ISSUE THREAD

**Issue by Mohron** [raoulvdberge/refinedstorageaddons#21]
Would you be willing to make the Wireless Crafting Grid's max power storage configurable like the controller is in refined storage?

Thank you for your consideration!

**Comment by raoulvdberge** [comment]
Yes! This will need some code for config syncing from server to client. I'm going to do the same for RS energy capacities soon.

**Comment by raoulvdberge** [comment]
Fixed for 1.14
