### ISSUE TITLE
Crash with Moving Wireless Crafting Grid into itself.

### ISSUE THREAD

**Issue by Origiginal** [raoulvdberge/refinedstorageaddons#26]
RSAddons version 0.3
RS version 1.5.33

You can't pick up the wireless crafting grid normally if you have the GUI opened, however you can move it with the number keys. 

Say the crafting grid is in your 1st hotbar slot, and then you open the gui and hover over the crafting grid and press 1 to move the wireless crafting grid into the crafting grid the game immediatley crashes.
After restarting the game and loading up the world the wireless crafting grid is nowhere to be seen
Full Crash Report: https://pastebin.com/2caUmNVD

**Comment by raoulvdberge** [comment]
Can you make this issue on the RS issue tracker as well, because this is also possible with normal wireless grids.

**Comment by raoulvdberge** [comment]
Fixed RS side in https://github.com/raoulvdberge/refinedstorage/commit/89b7d2bfc8371d05eb9d1a073b5c76435daf2075
