### ISSUE TITLE
Network bag is still used and should not be removed

### ISSUE THREAD

**Issue by roboderpy** [raoulvdberge/refinedstorageaddons#29]
Not sure about picker.

Network bag is basically quality of life thing, to not to carry thousands of satchels from various mods.

And infinite range transmitter is used too. If it is going to be removed, we gonna wait and switch back to EnderIO inventory panel which has infinite range version of remote panel.

**Comment by raoulvdberge** [comment]
These reasons do not warrant me changing my mind
