### ISSUE TITLE
Items in network not being shown + Crash

### ISSUE THREAD

**Issue by cheesealmighty** [raoulvdberge/refinedstorageaddons#30]
I didn't do anything in particular, but accessing my wireless crafting storage, and regular crafting storage panel shows no items in the system. Yet I can pull items to the crafting table using JEI. 

This doesn't happen every time, and didn't happen after an update or anything, exactly. It just started at some point and persists for a while, then eventually crashing. (Vanilla Fix catches the crashes, so I don't really crash)

Also, every time I open my crafting grid, whether wireless or not, there's always 9x9 mossy cobblestone in the crafting grid. Server reset, client reset doesn't seem to change the item. But after putting them back into the storage/inventory, crafting grid can be used. But when accessed again, defaults to 9x9 mossy cobble again.

https://paste.ubuntu.com/p/fY4mMgjVh6/

Any ideas?

**Comment by Jackzmc** [comment]
I've been having this type of problem too, no items in the grid show up, but I can still take them out with other means.
Not trying to hijack this issue but it seems like what I'm having. I also started getting crashes: https://puu.sh/AVi4Q/a0ad309257.mp4.

That disconnects me, but trying to shift+click recipes does crash me. My fix seems to be just restarting the server tho

**Comment by raoulvdberge** [comment]
I can't reproduce this.

**Comment by P3rf3ctXZer0** [comment]
I also have this issue and it is not fixed.
