### ISSUE TITLE
Wireless Crafting Grid does not have a crafting gui

### ISSUE THREAD

**Issue by Trellinane** [raoulvdberge/refinedstorageaddons#36]
Hello,

I made the wireless crafting grid and when I open it I do have access to my network but there is no crafting grid in the gui so I cannot craft anything wirelessly unless I have a pattern in my system for it.  I remember using this in previous versions and having a crafting grid so I could use things from my network to craft on the fly.  I did make double sure that I have the actual wireless "crafting" grid and not just a wireless grid.  I looked at the changelog and both the closed and open issues and did not see anything on this.

Minecraft: 1.12.2
Refined Storage 1.6.3
Refined Storage Addons 0.4
Forge 14.23.4.2739

**Comment by raoulvdberge** [comment]
Have you considered updating RS addons
