### ISSUE TITLE
Wireless Crafting Grid Duplication Glitch

### ISSUE THREAD

**Issue by Adaaaaam** [raoulvdberge/refinedstorageaddons#38]
Idk if this happens no matter what but I have been playing FTB Revelation and the wireless crafting grid can duplicate items by placing items in the crafting grid and clicking the X to clear. Then it will put double the amount of items back into the refined storage system. I don't want to cheat so this is annoying since i can no longer use that part of the mod. Please fix!

Other than that, great mod!

**Comment by raoulvdberge** [comment]
What versions are you using?

**Comment by Adaaaaam** [comment]
Minecraft version 1.12.2
FTB Revelation version 2.4.0
Refined Storage version 1.6.3
Refined Storage Addons version 0.4.1

**Comment by ComplainingSkelzie** [comment]
I am also having this issue with:
Minecraft 1.12.2
Forge 14.23.4.2760
Refined Storage 1.6.5
Refined Storage Addons 0.4.2

**Comment by raoulvdberge** [comment]
I can't reproduce this.

**Comment by TheVeyra** [comment]
Sorry if you didn't want this to be re-opened but I ran into the same issue and tested it in a new pack instance with nothing but RS and RSA. [I also recorded it happening](https://www.youtube.com/watch?v=7w2i16zsVq0&feature=youtu.be)

Minecraft - 1.12.2
Forge - 14.23.4.2760
Refined Storage - 1.6.5
Refined Storage Addons - 0.4.2

**Comment by xILikepuddingx** [comment]
Its only in SP. MP is fine

**Comment by raoulvdberge** [comment]
This has been fixed RS side.
