### ISSUE TITLE
Feature request: wear wireless crafting grid as a bauble + utilize keybinding

### ISSUE THREAD

**Issue by starlingfire** [raoulvdberge/refinedstorageaddons#40]
It would be great if we would wear the wireless crafting grid as a bauble, or at least set a keybinding to open it if it's in our inventory. This removes the necessity of having it in the hotbar.

For reference, this functionality exists in pa55w0rd's AE2 variant of this mod: https://github.com/p455w0rd/WirelessCraftingTerminal

Love the mod, thanks!

**Comment by raoulvdberge** [comment]
No sorry

**Comment by Jkosio23** [comment]
If you're just copying what the Wireless Crafting Terminal is doing but for RS, why not add this in?
