### ISSUE TITLE
Wireless Transmitter "Issue"

### ISSUE THREAD

**Issue by Lost-Ninja** [raoulvdberge/refinedstorageaddons#41]
Was about to report it being AWOL as I didn't see the changlog for it's removal...

Perhaps remove the section of the config that suggests that it is indeed missing.

Don't actually have any issue with it's loss, just difficult to know when something goes if the internal files still refer to it. :/

`infinitewirelesstransmitter {
    # The range of the Infinite Wireless Transmitter [range: 0 ~ 2147483647, default: 2147483647]
    I:infiniteWirelessTransmitterRange=2147483647

    # The energy used by the Infinite Wireless Transmitter [range: 0 ~ 2147483647, default: 1000]
    I:infiniteWirelessTransmitterUsage=1000
}

`

**Comment by raoulvdberge** [comment]
The config has been removed, it will no longer be generated in new files.

The config file just needs to be regenerated by your pack.
