### ISSUE TITLE
The game crashed whilst initializing game

### ISSUE THREAD

**Issue by Vampirian** [raoulvdberge/refinedstorageaddons#42]
hello I need help wen i start minecraft an error shows up (The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/raoulvdberge/refinedstorageaddons/block/BlockInfiniteWirelessTransmitte) please help me.

sorry for my bad Englisch I am from germany

**Comment by raoulvdberge** [comment]
Update all your mods!
