### ISSUE TITLE
[Suggestion] Wireless Pattern Grid

### ISSUE THREAD

**Issue by aranian** [raoulvdberge/refinedstorageaddons#44]
When setting up new machine rooms I often find myself teleporting between my main Grid setup and the new room, creating processing patterns and taking them to the room. While a Crafting Manager can help, these tend to get quite large and thus laggy (when scrolling).
A wireless version would help: Start a crafting task, check with the Crafting Monitor if it is running correctly, debug the machine setup and redo the pattern on the road, if necessary.
Another wish of mine would be a combination of the 3 (or with this, 4) wireless terminals into one, with tabs or buttons for switching between the modes. Space on the hotbar is always tight :)

**Comment by raoulvdberge** [comment]
no.
