### ISSUE TITLE
Crash with JEI recipe loading

### ISSUE THREAD

**Issue by SavageKiller13** [raoulvdberge/refinedstorageaddons#45]
How this happened. I can replicate the crash easily. The details are as Follows, while playing the modpack Ultimate Alchemy and using the Wireless Crafting Grid I am trying to shift click a recipe in from JEI and the crash or log would be saying I am sending too much packets.

**Comment by raoulvdberge** [comment]
This issue has been reported on the Refined Storage main repo already.
