### ISSUE TITLE
Opening wireless grids with the keybinding locks the active hot bar slot, even if that slot isn't the opened grid.

### ISSUE THREAD

**Issue by Artanis** [raoulvdberge/refinedstorageaddons#48]
*Version: 0.4.4*

### Replication

1. Have a Wireless Grid (or similar) in your inventory.
2. Assign a key to open that grid.
3. Select a slot on the hot bar that doesn't contain the Wireless Grid.
4. Open the Wireless Grid with the keybinding.

### Result

* Items cannot be moved into or out of the selected hot bar slot as long as the Wireless Grid is open.
* The Wireless Grid can be picked up, dropped out of the inventory, or moved to any slot except the selected hot bar slot, including into the storage network it is connected to.

### Expected Behavior

Opening a Wireless Grid or other wireless grid item should lock the inventory slot the opened grid occupies, rather than assume the currently selected hot bar slot has the open grid and locking that.

----

I'm sure this is for locking the grid in place when it is opened by right-clicking it, so that you can't accidentally put it into itself. However, when you open with the keybinding the selected slot could easily be something else, and it's a little confusing when suddenly a "random" item can't be picked up, or a "random" slot can't have an item moved into it while the grid is open.

As a curiosity, picked up items can be put into the locked slot if it is empty, and will then be locked in place until the Wireless Grid is closed.

**Comment by raoulvdberge** [comment]
Fixed for RS 1.7.1. Thanks for reporting.

https://github.com/raoulvdberge/refinedstorage/commit/b485c74503b84cb7b7f7f105ecbce566be9f520e
