### ISSUE TITLE
Infinite Wireless Transmitter

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorageaddons#5]

**Comment by LousyLynx** [comment]
I am interested in working on this. I only have 1 question. Would it be another transmitter block or an upgrade?

**Comment by raoulvdberge** [comment]
Another transmitter block, but this feature might be a sattelite based system, so I wouldn't recommend working on it yet.

**Comment by llloyd4** [comment]
I, for one, would love to see this after seeing AE2 has one through a third party addon mod.
