### ISSUE TITLE
Big recipe can crash Server

### ISSUE THREAD

**Issue by Imothep80** [raoulvdberge/refinedstorageaddons#55]
Version: 1.8.1

I start a big recipe. Forge Shutdown Server after 60 seconds lag.

latest.log: https://gist.github.com/Imothep80/1112278bb97a9c86b98f6d6ece9bf27e
crash.log: https://gist.github.com/Imothep80/e31adf928a598c56e3fea7831c979368

If you need more Information please tell me.

**Comment by raoulvdberge** [comment]
This is not related to RS Addons.
