### ISSUE TITLE
Duplication Bug with Wireless Crafting Terminal

### ISSUE THREAD

**Issue by ProfessorBiddle** [raoulvdberge/refinedstorageaddons#56]
If you use the hotkey to open the wireless crafting grid you can place items into the crafting area, drop the grid, and shift click infinite items into the RS system.

![ezgif-3-655efea8280a](https://user-images.githubusercontent.com/34872564/79382631-0c959780-7f21-11ea-8d01-ab14bfc5e1b1.gif)

**Comment by raoulvdberge** [comment]
fixed
