### ISSUE TITLE
[Feature request] Swap between outputs with same recipe in wireless crafting grid

### ISSUE THREAD

**Issue by dhasial** [raoulvdberge/refinedstorageaddons#96]
### Describe your enhancement

Within both a normal crafting table and RS's native grids, it is possible to craft different output items which share the same recipe. For example, it is possible to put 9 stone in any of these grids, and an arrow appears to toggle between crafting different output items, in my case either `Heavy Stone Bricks from Architect's Palette` or `Compressed Stone from Prefab`.

This feature does not appear when using the `Wireless Crafting Grid` and I'd like to see it implemented, especially considering its utility. I would hope that this feature would be relatively easy to implement since it already exists within the native RS grids.

**Comment by Darkere** [comment]
That feature is not part of RS. Find the mod and request they add support.
