### ISSUE TITLE
Italian localisation problem

### ISSUE THREAD

**Issue by BlackShadow77** [raoulvdberge/refinedstorageaddons#98]
### Describe the bug

I select italian from language option in minecraft and i expect to see applied also to the mod the italian lang file but in game the items remains in english.

The problem was also present in older version of the mod and i sent a pull request ( #91 ) to try to solve the bug.

### How can we reproduce this bug or crash?

1. Open minecraft
2. Change language to italian
3. Enter in a word
4. search on jei or creative tab items from the mod

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.1.7

### What Refined Storage Addons version is this happening on?

0.9.0

**Comment by raoulvdberge** [comment]
I cannot reproduce this on 1.20.4
